// Public professional summaries only. No private cases, metrics, images, or certificates.
export const career = [
  { company: 'Yuksel Saudia', period: 'March 2025 — Present', role: 'Senior QA/QC Engineer · Head Office', scope: 'Construction governance', summary: 'Corporate quality systems, controlled documentation, audit readiness and infrastructure reporting.', capabilities: ['QMS & ITP coordination', 'Cross-functional evidence review', 'Power BI & department coaching'] },
  { company: 'Eibla for Energy', period: 'August 2023 — March 2025', role: 'Senior QA/QC Engineer', scope: 'Electrical & mechanical manufacturing', summary: 'Quality leadership across mechanical manufacturing, electrical-panel assembly and warehouse operations.', capabilities: ['Incoming, process & final inspection', 'BOM and engineering-change control', 'Customer readiness & 8D'] },
  { company: 'El Araby Group', period: '2020 — 1 August 2023', role: 'Quality Control → Assistant Manager', scope: 'Cooking-appliance manufacturing', summary: 'Built factory QC systems and progressed to Assistant Manager, connecting team capability, inspection and process improvement.', capabilities: ['Appliance assembly & manufacturing', 'Calibration, MSA & SPC', 'First-piece release & traceability'] },
  { company: 'Freelance / Independent Engineering', period: 'May 2018 — January 2020', role: 'Freelance Mechanical Engineering', scope: 'Independent professional work', summary: 'Independent work from graduation, including SolidWorks training and engineering drawings, an ANSYS Fluent simulation project for an air ejector pump, and database development for local organizations.', capabilities: ['SolidWorks training & engineering drawings', 'ANSYS Fluent · air ejector pump project', 'Database development'] },
];
export const practice = { company: 'ProDigi Consult', role: 'Selected digital-solution work', summary: 'Workflow design, reporting and operational tools presented as a separate body of work. Individual cases identify their context and evidence.', capabilities: ['Digital workflows', 'Reporting & data quality', 'Operational tools'] };
export const routes = [
  { id: 'leadership', title: 'Quality leadership', label: 'Build the system. Develop the team.', summary: 'Quality planning, inspector capability, audit readiness and cross-functional problem solving.', example: 'At Yuksel Saudia, the context is corporate QMS/ITP coordination, controlled documentation and department coaching. At Eibla, quality leadership covered mechanical manufacturing, electrical-panel assembly and warehouse operations.', evidence: 'Team structures, quality plans, training approaches and corrective-action methods.', tools: ['QMS', '8D / CAPA', 'Skills matrices', 'Audit readiness'] },
  { id: 'inspection', title: 'Inspection & measurement', label: 'Make acceptance repeatable.', summary: 'Incoming, in-process and final inspection, calibration, reference samples and measurement-system analysis.', example: 'El Araby work included calibration, MSA, SPC and first-piece release. Eibla work covered incoming, process and final inspection, connecting engineering requirements to practical acceptance checks.', evidence: 'Inspection foundations, first-piece controls, equipment coordination and Minitab studies.', tools: ['Inspection plans', 'Calibration', 'Gage R&R', 'SPC'] },
  { id: 'improvement', title: 'Manufacturing improvement', label: 'Connect variation to action.', summary: 'Process trials, defect containment, controlled changeovers and data-led improvement across manufacturing operations.', example: 'Manufacturing work connects traceability, process control and structured root-cause analysis. Eibla includes customer-readiness and 8D methods; the separate Yuksel Saudia context includes Power BI reporting and cross-functional evidence review.', evidence: 'Process-control examples, traceability, capability analysis and structured improvement work.', tools: ['Root-cause analysis', 'DOE', 'COPQ', 'Power BI'] },
  { id: 'engineering', title: 'Engineering & release control', label: 'Keep the intended configuration.', summary: 'Drawing interpretation, SolidWorks reverse engineering, governing dimensions, BOM checks and development-sample release.', example: 'At Eibla, the work included BOM and engineering-change control. Public capability summaries cover drawing interpretation and development-sample release; detailed examples identify the company context and my specific contribution.', evidence: 'Documented engineering-quality coordination and assembly acceptance; each case defines Ahmed’s actual contribution.', tools: ['SolidWorks', 'BOM checks', 'Change control', 'Development samples'] },
];
export const credentials = [
  { title: 'ISO 9001:2015 Auditor / Lead Auditor training', issuer: 'SGS · CQI/IRCA-certified course', detail: 'Exam passed January 2026. Training completion is distinct from professional auditor registration.' },
  { title: 'Lean Six Sigma Green Belt', issuer: 'Attic / El Araby · March 2021', detail: 'Applied statistical problem solving and manufacturing improvement.' },
  { title: 'Exercising Leadership', issuer: 'HarvardX · September 2025', detail: 'Professional learning supporting team and organizational leadership.' },
  { title: 'Operations Management: Quality and Supply Chain', issuer: 'University of Illinois · May 2025', detail: 'Professional learning in quality and operational systems.' },
];
